// <auto-generated />
namespace LinqToEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ver30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver30));
        
        string IMigrationMetadata.Id
        {
            get { return "201703300931075_ver3.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
