// <auto-generated />
namespace LinqToEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ver80 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver80));
        
        string IMigrationMetadata.Id
        {
            get { return "201703310246049_ver8.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
