//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Services
{
    using System;
    using System.Collections.Generic;
    using QK.QAPP.Entity;
    using QK.QAPP.Infrastructure.Data.EFRepository.Repository;
    using QK.QAPP.IServices;
    
    public partial class APP_EXTEND_RELATIONSERVICE : RepositoryBase<APP_EXTEND_RELATION>, IAPP_EXTEND_RELATIONSERVICE 
    
    
    {
    
    public APP_EXTEND_RELATIONSERVICE(IUnitOfWork unitOfWork): base(unitOfWork){}
    	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        }
}
