//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Services
{
    using System;
    using System.Collections.Generic;
    using QK.QAPP.Entity;
    using QK.QAPP.Infrastructure.Data.EFRepository.Repository;
    using QK.QAPP.IServices;
    
    public partial class APP_DFORM_FIELDATTRIBUTESERVICE : RepositoryBase<APP_DFORM_FIELDATTRIBUTE>, IAPP_DFORM_FIELDATTRIBUTESERVICE 
    
    
    {
    
    public APP_DFORM_FIELDATTRIBUTESERVICE(IUnitOfWork unitOfWork): base(unitOfWork){}
    	
        	
        	
        	
        
    }
}
