// <auto-generated />
namespace CQRSUnit.Migrations.ReaderMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ver10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver10));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060938205_ver1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
