//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMLModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lodging
    {
        public int LodgingId { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Activities { get; set; }
        public string Entertainment { get; set; }
        public string Discriminator { get; set; }
    }
}
