//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMLModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> Blog_Id { get; set; }
        public Nullable<int> UpdatedBy_Id { get; set; }
        public Nullable<int> CreatedBy_Id { get; set; }
    
        public virtual blog blog { get; set; }
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
    }
}
