//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using QK.QAPP.Entity;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class APPEntities : DbContext
    {
        public APPEntities()
            : base("name=APPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APP_BANKCARD> APP_BANKCARD { get; set; }
        public DbSet<APP_JOB> APP_JOB { get; set; }
        public DbSet<APP_LOAN> APP_LOAN { get; set; }
        public DbSet<APP_SALES> APP_SALES { get; set; }
        public DbSet<APP_STAFF_ONLY> APP_STAFF_ONLY { get; set; }
        public DbSet<APP_DFORM_FIELDATTRIBUTE> APP_DFORM_FIELDATTRIBUTE { get; set; }
        public DbSet<APP_DFORM_FORMBUILDER> APP_DFORM_FORMBUILDER { get; set; }
        public DbSet<APP_DFORM_FORMFIELD> APP_DFORM_FORMFIELD { get; set; }
        public DbSet<APP_DFORM_FORMINFO> APP_DFORM_FORMINFO { get; set; }
        public DbSet<APP_CONTACT> APP_CONTACT { get; set; }
        public DbSet<APP_MAIN> APP_MAIN { get; set; }
        public DbSet<FL_BIZ> FL_BIZ { get; set; }
        public DbSet<FL_LIST> FL_LIST { get; set; }
        public DbSet<APP_FILE_CHECK> APP_FILE_CHECK { get; set; }
        public DbSet<V_APPMAIN> V_APPMAIN { get; set; }
        public DbSet<APP_NR_LIST> APP_NR_LIST { get; set; }
        public DbSet<APP_QUEUE> APP_QUEUE { get; set; }
        public DbSet<APP_CITY> APP_CITY { get; set; }
        public DbSet<APP_MSGBOX_USER> APP_MSGBOX_USER { get; set; }
        public DbSet<APP_MSGBOX> APP_MSGBOX { get; set; }
        public DbSet<APP_CUSTOMER> APP_CUSTOMER { get; set; }
        public DbSet<APP_APPLY_SEQUENCE> APP_APPLY_SEQUENCE { get; set; }
        public DbSet<APP_GLOBALCONFIG> APP_GLOBALCONFIG { get; set; }
        public DbSet<APP_AEO> APP_AEO { get; set; }
        public DbSet<APP_AUTH> APP_AUTH { get; set; }
        public DbSet<APP_EXTEND_CONFIG> APP_EXTEND_CONFIG { get; set; }
        public DbSet<APP_EXTEND_RELATION> APP_EXTEND_RELATION { get; set; }
        public DbSet<APP_CARPRICE> APP_CARPRICE { get; set; }
        public DbSet<APP_FORBIDEN_AREA> APP_FORBIDEN_AREA { get; set; }
        public DbSet<APP_CARINFO> APP_CARINFO { get; set; }
        public DbSet<PAD_CARJUDGE> PAD_CARJUDGE { get; set; }
        public DbSet<APP_CARVALUATORS> APP_CARVALUATORS { get; set; }
        public DbSet<APP_QUEUE_ASSESS> APP_QUEUE_ASSESS { get; set; }
        public DbSet<APP_CARAGENCY> APP_CARAGENCY { get; set; }
        public DbSet<PRE_APP_AUTH> PRE_APP_AUTH { get; set; }
        public DbSet<PRE_APP_BANKCARD> PRE_APP_BANKCARD { get; set; }
        public DbSet<PRE_APP_CUSTOMER> PRE_APP_CUSTOMER { get; set; }
        public DbSet<PRE_APP_JOB> PRE_APP_JOB { get; set; }
        public DbSet<PRE_APP_LOAN> PRE_APP_LOAN { get; set; }
        public DbSet<PRE_APP_MAIN> PRE_APP_MAIN { get; set; }
        public DbSet<PRE_APP_STAFF_ONLY> PRE_APP_STAFF_ONLY { get; set; }
        public DbSet<V_PRE_APPMAIN> V_PRE_APPMAIN { get; set; }
        public DbSet<APP_HOUSE> APP_HOUSE { get; set; }
        public DbSet<PRE_APP_CARINFO> PRE_APP_CARINFO { get; set; }
        public DbSet<V_APP_CONTRACT> V_APP_CONTRACT { get; set; }
        public DbSet<APP_CITY_PRODUCT> APP_CITY_PRODUCT { get; set; }
        public DbSet<APP_QUANT> APP_QUANT { get; set; }
        public DbSet<APP_QUANT_TEMP> APP_QUANT_TEMP { get; set; }
    
        public virtual int P_APP_APPLYNUMBER(string i_VC_SEQCODE, string i_VC_CITYCODE, string i_VC_PRONUM, ObjectParameter o_VC_RETURNNUM, ObjectParameter o_VC_ERRORMSG)
        {
            var i_VC_SEQCODEParameter = i_VC_SEQCODE != null ?
                new ObjectParameter("I_VC_SEQCODE", i_VC_SEQCODE) :
                new ObjectParameter("I_VC_SEQCODE", typeof(string));
    
            var i_VC_CITYCODEParameter = i_VC_CITYCODE != null ?
                new ObjectParameter("I_VC_CITYCODE", i_VC_CITYCODE) :
                new ObjectParameter("I_VC_CITYCODE", typeof(string));
    
            var i_VC_PRONUMParameter = i_VC_PRONUM != null ?
                new ObjectParameter("I_VC_PRONUM", i_VC_PRONUM) :
                new ObjectParameter("I_VC_PRONUM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_APP_APPLYNUMBER", i_VC_SEQCODEParameter, i_VC_CITYCODEParameter, i_VC_PRONUMParameter, o_VC_RETURNNUM, o_VC_ERRORMSG);
        }
    
        public virtual int P_APP_APPLYNUMBER_EXTEND(string i_VC_SEQCODE, string i_VC_CITYCODE, string i_VC_PRONUM, string i_VC_OPETYPE, ObjectParameter o_VC_RETURNNUM, ObjectParameter o_VC_ERRORMSG)
        {
            var i_VC_SEQCODEParameter = i_VC_SEQCODE != null ?
                new ObjectParameter("I_VC_SEQCODE", i_VC_SEQCODE) :
                new ObjectParameter("I_VC_SEQCODE", typeof(string));
    
            var i_VC_CITYCODEParameter = i_VC_CITYCODE != null ?
                new ObjectParameter("I_VC_CITYCODE", i_VC_CITYCODE) :
                new ObjectParameter("I_VC_CITYCODE", typeof(string));
    
            var i_VC_PRONUMParameter = i_VC_PRONUM != null ?
                new ObjectParameter("I_VC_PRONUM", i_VC_PRONUM) :
                new ObjectParameter("I_VC_PRONUM", typeof(string));
    
            var i_VC_OPETYPEParameter = i_VC_OPETYPE != null ?
                new ObjectParameter("I_VC_OPETYPE", i_VC_OPETYPE) :
                new ObjectParameter("I_VC_OPETYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_APP_APPLYNUMBER_EXTEND", i_VC_SEQCODEParameter, i_VC_CITYCODEParameter, i_VC_PRONUMParameter, i_VC_OPETYPEParameter, o_VC_RETURNNUM, o_VC_ERRORMSG);
        }
    }
}
