//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_MAIN : BasicEntity
    {
        public APP_MAIN(): base(false){
                this.APP_BANKCARD = new HashSet<APP_BANKCARD>();
            this.APP_JOB = new HashSet<APP_JOB>();
            this.APP_LOAN = new HashSet<APP_LOAN>();
            this.APP_STAFF_ONLY = new HashSet<APP_STAFF_ONLY>();
            this.APP_NR_LIST = new HashSet<APP_NR_LIST>();
            this.APP_QUEUE = new HashSet<APP_QUEUE>();
            this.APP_CUSTOMER = new HashSet<APP_CUSTOMER>();
            this.APP_AUTH = new HashSet<APP_AUTH>();
            this.APP_CARINFO = new HashSet<APP_CARINFO>();
            this.APP_HOUSE = new HashSet<APP_HOUSE>();
            this.APP_QUANT = new HashSet<APP_QUANT>();
        }
        public APP_MAIN(bool isGenerated = false): base(isGenerated)
        {
            this.APP_BANKCARD = new HashSet<APP_BANKCARD>();
            this.APP_JOB = new HashSet<APP_JOB>();
            this.APP_LOAN = new HashSet<APP_LOAN>();
            this.APP_STAFF_ONLY = new HashSet<APP_STAFF_ONLY>();
            this.APP_NR_LIST = new HashSet<APP_NR_LIST>();
            this.APP_QUEUE = new HashSet<APP_QUEUE>();
            this.APP_CUSTOMER = new HashSet<APP_CUSTOMER>();
            this.APP_AUTH = new HashSet<APP_AUTH>();
            this.APP_CARINFO = new HashSet<APP_CARINFO>();
            this.APP_HOUSE = new HashSet<APP_HOUSE>();
            this.APP_QUANT = new HashSet<APP_QUANT>();
        }
    
            
    	 [Sequence("SEQ_APP_MAIN")]
    		
         public long ID { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public string LOGO { get; set; }     
            
    		
         public string PRODUCT_CODE { get; set; }     
            
    		
         public string PRODUCT_NAME { get; set; }     
            
    		
         public string AREA_CODE { get; set; }     
            
    		
         public string AREA_NAME { get; set; }     
            
    		
         public string STORE_CODE { get; set; }     
            
    		
         public string STORE_NAME { get; set; }     
            
    		
         public string ENTRY_NO { get; set; }     
            
    		
         public string APP_STATUS { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string ENTRYNAME { get; set; }     
            
    		
         public string APPLY_CITY_CODE { get; set; }     
            
    		
         public string ENTRY_ORG_CODE { get; set; }     
            
    		
         public string ENTRY_ORG_NAME { get; set; }     
            
    		
         public string IS_VIP { get; set; }     
            
    		
         public string IS_REPEAT { get; set; }     
            
    		
         public string PRODUCT_SUIT_CROUD { get; set; }     
            
    		
         public string APP_NR_SD_STATUS { get; set; }     
            
    		
         public string APP_APPR1_SD_STATUS { get; set; }     
            
    		
         public string CUSTOMERTYPE { get; set; }     
            
    		
         public Nullable<short> NR_SEQ { get; set; }     
            
    		
         public string IS_AUDIT_FLAG { get; set; }     
            
    		
         public string IS_AUDIT_APPROVE_FLAG { get; set; }     
            
    		
         public string STATUS_PHASE { get; set; }     
            
    		
         public string PROD_VERSION { get; set; }     
            
    		
         public Nullable<decimal> DECISION_SCORE { get; set; }     
            
    		
         public string DECISION_MODEL { get; set; }     
            
    		
         public string APPLY_AREA_CODE { get; set; }     
            
    		
         public Nullable<long> PRE_APP_ID { get; set; }     
            
    		
         public Nullable<System.DateTime> GIVE_LOAN_TIME { get; set; }     
            
    		
         public Nullable<System.DateTime> BACK_LOAN_TIME { get; set; }     
            
    		
         public string HAS_EXTEND { get; set; }     
            
    		
         public string CREDIT_CHANNEL_CODE { get; set; }     
            
    		
         public string OPENID { get; set; }     
            
    		
         public Nullable<System.DateTime> SUBMIT_TIME { get; set; }     
            
    		
         public string OVERDUE_STATUS { get; set; }     
            
    		
         public string MOBILE_HISTORY_STATUS { get; set; }     
            
    		
         public string CONTRACT_IS_CREATE { get; set; }     
            
    		
         public string PBOC_STATUS { get; set; }     
            
    		
         public string NETBANK_STATUS { get; set; }     
            
    		
         public string FUND_STATUS { get; set; }     
        public virtual ICollection<APP_BANKCARD> APP_BANKCARD { get; set; }
        public virtual ICollection<APP_JOB> APP_JOB { get; set; }
        public virtual ICollection<APP_LOAN> APP_LOAN { get; set; }
        public virtual ICollection<APP_STAFF_ONLY> APP_STAFF_ONLY { get; set; }
        public virtual ICollection<APP_NR_LIST> APP_NR_LIST { get; set; }
        public virtual ICollection<APP_QUEUE> APP_QUEUE { get; set; }
        public virtual ICollection<APP_CUSTOMER> APP_CUSTOMER { get; set; }
        public virtual ICollection<APP_AUTH> APP_AUTH { get; set; }
        public virtual ICollection<APP_CARINFO> APP_CARINFO { get; set; }
        public virtual ICollection<APP_HOUSE> APP_HOUSE { get; set; }
        public virtual ICollection<APP_QUANT> APP_QUANT { get; set; }
        
    }
}
