//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_FORBIDEN_AREA : BasicEntity
    {
         public APP_FORBIDEN_AREA(): base(false){ }
         public APP_FORBIDEN_AREA(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_FORBIDEN_AREA")]
    		
         public long ID { get; set; }     
            
    		
         public string CITY_CODE { get; set; }     
            
    		
         public string FORBIDEN_AREA { get; set; }     
            
    		
         public string FORBIDEN_ID_START { get; set; }     
            
    		
         public string PRODUCT_LOGO { get; set; }     
            
    		
         public string JUST_FOR_CITY { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public string PROVINCE_CODE { get; set; }     
            
    		
         public string PRPVINCE_CITY { get; set; }     
        
    }
}
