//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CARINFO : BasicEntity
    {
         public APP_CARINFO(): base(false){ }
         public APP_CARINFO(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_CARINFO")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> APP_ID { get; set; }     
            
    		
         public string CAR_BRAND { get; set; }     
            
    		
         public string CAR_FACTORY { get; set; }     
            
    		
         public string CAR_KIND { get; set; }     
            
    		
         public string PRODUCT_DATE { get; set; }     
            
    		
         public string CAR_COLOR { get; set; }     
            
    		
         public string VEHICLE_NO { get; set; }     
            
    		
         public string ENGINE_NO { get; set; }     
            
    		
         public string VIN_NO { get; set; }     
            
    		
         public string DRIVE_OWNER { get; set; }     
            
    		
         public string PERMITTED_OWNER { get; set; }     
            
    		
         public string RELATION_OWNER { get; set; }     
            
    		
         public string PAPER_NO { get; set; }     
            
    		
         public string USE_NATURE { get; set; }     
            
    		
         public string OTHERCAR_BRAND { get; set; }     
            
    		
         public string OTHERCAR_FACTORY { get; set; }     
            
    		
         public Nullable<decimal> VEHICLE_MILES { get; set; }     
            
    		
         public Nullable<decimal> CAR_PRICE { get; set; }     
            
    		
         public string CAR_SERIES { get; set; }     
            
    		
         public Nullable<decimal> CAR_SELLINGPRICE { get; set; }     
            
    		
         public string CARINFO_TYPE { get; set; }     
            
    		
         public Nullable<System.DateTime> MANUFACTURE_DATE { get; set; }     
            
    		
         public string CAR_MODEL { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
