//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_GLOBALCONFIG : BasicEntity
    {
        public APP_GLOBALCONFIG(): base(false){
                this.APP_GLOBALCONFIG1 = new HashSet<APP_GLOBALCONFIG>();
        }
        public APP_GLOBALCONFIG(bool isGenerated = false): base(isGenerated)
        {
            this.APP_GLOBALCONFIG1 = new HashSet<APP_GLOBALCONFIG>();
        }
    
            
    	 [Sequence("SEQ_APP_GLOBALCONFIG")]
    		
         public long ID { get; set; }     
            
    		
         public string KEY { get; set; }     
            
    		
         public string VALUE { get; set; }     
            
    		
         public string CATEGORY { get; set; }     
            
    		
         public string REMARK { get; set; }     
            
    		
         public Nullable<long> SORT { get; set; }     
            
    		
         public Nullable<long> PARENT { get; set; }     
            
    		
         public string PLATFORM { get; set; }     
        public virtual ICollection<APP_GLOBALCONFIG> APP_GLOBALCONFIG1 { get; set; }
        public virtual APP_GLOBALCONFIG APP_GLOBALCONFIG2 { get; set; }
        
    }
}
