//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CONTACT : BasicEntity
    {
         public APP_CONTACT(): base(false){ }
         public APP_CONTACT(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_CONTACT")]
    		
         public long ID { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string RELATIONSHIP { get; set; }     
            
    		
         public string RELATIONSHIP_MEMO { get; set; }     
            
    		
         public string NAME { get; set; }     
            
    		
         public string MOBILE { get; set; }     
            
    		
         public string COM_NAME { get; set; }     
            
    		
         public string COM_DEPT { get; set; }     
            
    		
         public string COM_POSITION { get; set; }     
            
    		
         public string COM_PROVICE { get; set; }     
            
    		
         public string COM_CITY { get; set; }     
            
    		
         public string COM_ADDRESS { get; set; }     
            
    		
         public string CON_ID_NO { get; set; }     
            
    		
         public string CON_ID_TYPE { get; set; }     
            
    		
         public string CONTACT_PROPERTY { get; set; }     
            
    		
         public string RESIDENT_PROVINCE { get; set; }     
            
    		
         public string RESIDENT_CITY { get; set; }     
            
    		
         public string RESIDENT_ADDRESS { get; set; }     
            
    		
         public string REGISTER_PROVINCE { get; set; }     
            
    		
         public string REGISTER_CITY { get; set; }     
            
    		
         public string REGISTER_ADDRESS { get; set; }     
        
    }
}
