//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_QUANT_TEMP : BasicEntity
    {
         public APP_QUANT_TEMP(): base(false){ }
         public APP_QUANT_TEMP(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_QUANT_TEMP")]
    		
         public long ID { get; set; }     
            
    		
         public string APPLY_NUMBER { get; set; }     
            
    		
         public string CONTRACT_ID { get; set; }     
            
    		
         public string NAME { get; set; }     
            
    		
         public string ID_NO { get; set; }     
            
    		
         public string MOBILE { get; set; }     
            
    		
         public string ADDRESS { get; set; }     
            
    		
         public string BANK { get; set; }     
            
    		
         public string BANK_CARD { get; set; }     
            
    		
         public string BANK_PROVINCE { get; set; }     
            
    		
         public string BANK_CITY { get; set; }     
            
    		
         public string APPLY_AMT { get; set; }     
            
    		
         public string TERMS { get; set; }     
            
    		
         public string CREDIT_SCORE { get; set; }     
            
    		
         public string REPAYMENT_PLAN { get; set; }     
            
    		
         public string SUBMIT_DATE { get; set; }     
            
    		
         public string LENDING_DATE { get; set; }     
            
    		
         public string HAS_LENDING { get; set; }     
            
    		
         public string FAIL_REASON { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string HANDLE_STATUS { get; set; }     
        
    }
}
