//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_QUEUE : BasicEntity
    {
         public APP_QUEUE(): base(false){ }
         public APP_QUEUE(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_QUEUE")]
    		
         public long ID { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public string NAME { get; set; }     
            
    		
         public string GENDER { get; set; }     
            
    		
         public Nullable<short> AGE { get; set; }     
            
    		
         public string ID_NO { get; set; }     
            
    		
         public string ID_TYPE { get; set; }     
            
    		
         public string LOGO { get; set; }     
            
    		
         public string PRODUCT_CODE { get; set; }     
            
    		
         public string PRODUCT_NAME { get; set; }     
            
    		
         public string COM_NAME { get; set; }     
            
    		
         public Nullable<decimal> APPLY_AMT { get; set; }     
            
    		
         public string PAY_TYPE { get; set; }     
            
    		
         public Nullable<System.DateTime> DATE_APPLY { get; set; }     
            
    		
         public string SALES_NO { get; set; }     
            
    		
         public string SALES_NAME { get; set; }     
            
    		
         public string AREA_CODE { get; set; }     
            
    		
         public string AREA_NAME { get; set; }     
            
    		
         public string STORE_CODE { get; set; }     
            
    		
         public string STORE_NAME { get; set; }     
            
    		
         public string ENTRY_NO { get; set; }     
            
    		
         public string DECISION_NO_FIRST { get; set; }     
            
    		
         public string MANUAL_DECISION { get; set; }     
            
    		
         public string ES_DECISION { get; set; }     
            
    		
         public string APP_STATUS { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string DCOUT_VIP { get; set; }     
            
    		
         public string IS_REPEAT { get; set; }     
            
    		
         public string ENTRY_NAME { get; set; }     
            
    		
         public string DECISION_NAME { get; set; }     
            
    		
         public string CSAD_NO { get; set; }     
            
    		
         public string CSAD_NAME { get; set; }     
            
    		
         public Nullable<decimal> CONTRACT_AMT { get; set; }     
            
    		
         public string DO_ACTION { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string APP_STATUS_DONE { get; set; }     
            
    		
         public string APP_NR_SD_STATUS { get; set; }     
            
    		
         public string APP_APPR1_SD_STATUS { get; set; }     
            
    		
         public string DES_RUNNING_TAG { get; set; }     
            
    		
         public string DECISION_NO_FINAL { get; set; }     
            
    		
         public string FRAUD_NO { get; set; }     
            
    		
         public Nullable<short> QUEUE_ORDER { get; set; }     
            
    		
         public Nullable<decimal> STATUS_ORDER { get; set; }     
            
    		
         public Nullable<decimal> LOAN_AMT { get; set; }     
            
    		
         public Nullable<short> TERMS { get; set; }     
            
    		
         public string DECISION_CODE { get; set; }     
            
    		
         public string LATEST_APP_STATUS { get; set; }     
            
    		
         public string LATEST_ACTION { get; set; }     
            
    		
         public string DECISION_NO_HIST { get; set; }     
            
    		
         public string APPROVE_NAME { get; set; }     
            
    		
         public string FRAUD_NAME { get; set; }     
            
    		
         public string DCOUT_IS_AUTO_FINAL { get; set; }     
            
    		
         public string CUSTOMERTYPE { get; set; }     
            
    		
         public string DECISION_NO_FIRST_HIST { get; set; }     
            
    		
         public string IS_FINAL { get; set; }     
            
    		
         public string IS_AUDIT_FLAG { get; set; }     
            
    		
         public string IS_AUDIT_APPROVE_FLAG { get; set; }     
            
    		
         public string IS_AUDO_FINAL { get; set; }     
            
    		
         public string STATUS_PHASE { get; set; }     
            
    		
         public string APPLY_CITY_CODE { get; set; }     
            
    		
         public string ENTRY_ORG_CODE { get; set; }     
            
    		
         public string ENTRYORGNAME { get; set; }     
            
    		
         public string IS_LOCK { get; set; }     
            
    		
         public string IS_FIRST_LOCK { get; set; }     
            
    		
         public string IS_FINAL_LOCK { get; set; }     
            
    		
         public string IS_FRAUD_LOCK { get; set; }     
            
    		
         public string ENTRY_CHK_NO { get; set; }     
            
    		
         public string ENTRY_CHK_NAME { get; set; }     
            
    		
         public string DECISION_NO_ENTRY_CHK_HIST { get; set; }     
            
    		
         public string PROC_INS_ID { get; set; }     
            
    		
         public string TASK_ID { get; set; }     
            
    		
         public string DISP_STATUS { get; set; }     
            
    		
         public string PROCESS_TEMPLATE { get; set; }     
            
    		
         public string APP_TYPE { get; set; }     
            
    		
         public string VERSION { get; set; }     
            
    		
         public string APPLY_CITY_NAME { get; set; }     
            
    		
         public string MOBILE_PHONE_NO { get; set; }     
            
    		
         public string DEALER_CODE { get; set; }     
            
    		
         public string DEALER_NAME { get; set; }     
            
    		
         public string IS_RE_APPLICATION { get; set; }     
            
    		
         public Nullable<decimal> BILLING_AMT { get; set; }     
            
    		
         public string VEHICLE_NO { get; set; }     
            
    		
         public string COMPLETE_IMAGE { get; set; }     
            
    		
         public string DECISION_NO_FIELD_NO { get; set; }     
            
    		
         public string DECISION_NO_FIELD_NAME { get; set; }     
            
    		
         public string DECISION_NO_FIELD_HIST { get; set; }     
            
    		
         public string DECISION_NO_ASSESS_NO { get; set; }     
            
    		
         public string DECISION_NO_ASSESS_NAME { get; set; }     
            
    		
         public string DECISION_NO_ASSESS_HIST { get; set; }     
            
    		
         public string BANK_CARD_NUMBER { get; set; }     
            
    		
         public string PRODUCT_TYPE { get; set; }     
            
    		
         public string APPLY_LOGO { get; set; }     
            
    		
         public string APPLY_PRODUCT_CODE { get; set; }     
            
    		
         public string APPLY_PRODUCT_NAME { get; set; }     
            
    		
         public Nullable<short> APPLY_TERMS { get; set; }     
            
    		
         public string DCIN_REFUSE_CODE { get; set; }     
            
    		
         public string PBOC_STATUS { get; set; }     
            
    		
         public string ASSESS_NO { get; set; }     
            
    		
         public string ASSESS_NAME { get; set; }     
            
    		
         public string APPL_CDE { get; set; }     
            
    		
         public string APPL_SEQ { get; set; }     
            
    		
         public string LIST_MESSAGE { get; set; }     
            
    		
         public string IMAGE_MESSAGE { get; set; }     
            
    		
         public string IS_LIST_SYNC { get; set; }     
            
    		
         public string IS_IMAGE_SYNC { get; set; }     
            
    		
         public string HAVE_DONE { get; set; }     
            
    		
         public Nullable<decimal> CAR_DECISION_AMT { get; set; }     
            
    		
         public string CHANNEL_COOPERATION { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
