//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_LOAN : BasicEntity
    {
         public APP_LOAN(): base(false){ }
         public APP_LOAN(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_LOAN")]
    		
         public long ID { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string LOAN_PURPOSE { get; set; }     
            
    		
         public string MEMO_OF_LOAN_PURPOSE_OTHER { get; set; }     
            
    		
         public string CAR_BRAND_BUYING { get; set; }     
            
    		
         public string CAR_MODEL_BUYING { get; set; }     
            
    		
         public Nullable<decimal> CAR_PRICE_BUYING { get; set; }     
            
    		
         public Nullable<decimal> APPLY_AMT { get; set; }     
            
    		
         public Nullable<decimal> CREDITLIMITADVICE { get; set; }     
            
    		
         public Nullable<decimal> LOAN_AMT { get; set; }     
            
    		
         public Nullable<decimal> LOAN_AMT_OF_CONTRACT { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_MONTHLY_ACCEPTABLE { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_FIRST_MONTHLY { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_LAST_MONTHLY { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_MONTHLY { get; set; }     
            
    		
         public Nullable<decimal> DEFAULT_INTEREST_RATIO { get; set; }     
            
    		
         public Nullable<decimal> LATE_FEE_RATIO { get; set; }     
            
    		
         public Nullable<decimal> PREPAYMENT_RATIO { get; set; }     
            
    		
         public Nullable<decimal> SERVICE_CHARGE_RATIO { get; set; }     
            
    		
         public Nullable<decimal> CONSULTATION_CHARGE_RATIO { get; set; }     
            
    		
         public string RATE_TYPE { get; set; }     
            
    		
         public Nullable<short> TERMS { get; set; }     
            
    		
         public Nullable<decimal> RATE { get; set; }     
            
    		
         public string PAYTYPE { get; set; }     
            
    		
         public string CURRENCY { get; set; }     
            
    		
         public Nullable<decimal> RESERVES_RATIO { get; set; }     
            
    		
         public Nullable<decimal> SERVICE_CHARGE_AMT { get; set; }     
            
    		
         public Nullable<decimal> CONSULTATION_CHARGE_AMT { get; set; }     
            
    		
         public Nullable<decimal> RESERVES_AMT { get; set; }     
            
    		
         public Nullable<decimal> RISK_RATIO { get; set; }     
            
    		
         public Nullable<decimal> RISK_AMT { get; set; }     
            
    		
         public Nullable<decimal> EXTEND_AMT_OF_CONTRACT { get; set; }     
            
    		
         public string CAR_CHARACTERISTIC { get; set; }     
            
    		
         public Nullable<decimal> CAR_PRICE_ADVISE { get; set; }     
            
    		
         public Nullable<decimal> CAR_DOWN_PAYMENT { get; set; }     
            
    		
         public Nullable<decimal> CHANNEL_EXPENSE_RATIO { get; set; }     
            
    		
         public Nullable<decimal> CAR_DECISION_AMT { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
