//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_DFORM_FIELDATTRIBUTE : BasicEntity
    {
         public APP_DFORM_FIELDATTRIBUTE(): base(false){ }
         public APP_DFORM_FIELDATTRIBUTE(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_DFORM_FIELDATTRIBUTE")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> FORMFIELD_ID { get; set; }     
            
    		
         public string ATTRIBUTE_KEY { get; set; }     
            
    		
         public string ATTRIBUTE_VALUE { get; set; }     
        public virtual APP_DFORM_FORMFIELD APP_DFORM_FORMFIELD { get; set; }
        
    }
}
