//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CITY : BasicEntity
    {
         public APP_CITY(): base(false){ }
         public APP_CITY(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_CITY")]
    		
         public long ID { get; set; }     
            
    		
         public string CITY_NAME { get; set; }     
            
    		
         public string COMPANY_CODE { get; set; }     
            
    		
         public string AREA_PROVINCE { get; set; }     
            
    		
         public string AREA_CITY { get; set; }     
            
    		
         public Nullable<short> ENABLE { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATE_TIME { get; set; }     
            
    		
         public Nullable<System.DateTime> UPDATE_TIME { get; set; }     
            
    		
         public string CITY_CODE { get; set; }     
            
    		
         public string PRODUCT_CODE { get; set; }     
            
    		
         public string CACHE_FLAG { get; set; }     
            
    		
         public string AREA_CODE { get; set; }     
            
    		
         public string PLATFORM { get; set; }     
        
    }
}
