//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_DFORM_FORMFIELD : BasicEntity
    {
        public APP_DFORM_FORMFIELD(): base(false){
                this.APP_DFORM_FIELDATTRIBUTE = new HashSet<APP_DFORM_FIELDATTRIBUTE>();
        }
        public APP_DFORM_FORMFIELD(bool isGenerated = false): base(isGenerated)
        {
            this.APP_DFORM_FIELDATTRIBUTE = new HashSet<APP_DFORM_FIELDATTRIBUTE>();
        }
    
            
    	 [Sequence("SEQ_APP_DFORM_FORMFIELD")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> FORMINFO_ID { get; set; }     
            
    		
         public string FIELD_KEY { get; set; }     
            
    		
         public string FIELD_DISPLAYNAME { get; set; }     
            
    		
         public string FIELD_TYPE { get; set; }     
            
    		
         public Nullable<short> FIELD_ROWSPAN { get; set; }     
            
    		
         public string MAPPER_TABLE { get; set; }     
            
    		
         public string MAPPER_TABLEFIELD { get; set; }     
            
    		
         public string FIELD_GROUP { get; set; }     
            
    		
         public Nullable<short> FIELD_SORT { get; set; }     
            
    		
         public string FIELD_REQUIRED { get; set; }     
            
    		
         public string ISDISABLED { get; set; }     
            
    		
         public string ENABLE { get; set; }     
        public virtual ICollection<APP_DFORM_FIELDATTRIBUTE> APP_DFORM_FIELDATTRIBUTE { get; set; }
        public virtual APP_DFORM_FORMINFO APP_DFORM_FORMINFO { get; set; }
        
    }
}
