//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_STAFF_ONLY : BasicEntity
    {
         public APP_STAFF_ONLY(): base(false){ }
         public APP_STAFF_ONLY(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_STAFF_ONLY")]
    		
         public long ID { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string CHANNEL_CODE { get; set; }     
            
    		
         public string CHANNEL_NAME { get; set; }     
            
    		
         public string RECOMMEND_PERSON_CODE { get; set; }     
            
    		
         public string RECOMMEND_PERSON_NAME { get; set; }     
            
    		
         public string RECOMMEND_PERSON_TEL { get; set; }     
            
    		
         public string SALES_NAME { get; set; }     
            
    		
         public string SALES_CODE { get; set; }     
            
    		
         public Nullable<System.DateTime> SALES_SIGNATURE { get; set; }     
            
    		
         public string CSAD_CODE { get; set; }     
            
    		
         public string CSAD_NAME { get; set; }     
            
    		
         public string MEMO { get; set; }     
            
    		
         public string NR_MEMO_FROM_DECISION { get; set; }     
            
    		
         public string NR_MEMO_FROM_SALES { get; set; }     
            
    		
         public string MOTO_NO { get; set; }     
            
    		
         public string MOTO_NAME { get; set; }     
            
    		
         public string SALES_MOBILE { get; set; }     
            
    		
         public string CREDIT_CODE { get; set; }     
            
    		
         public string CREDIT_NAME { get; set; }     
            
    		
         public string BUSINESS_DEPARTMENT { get; set; }     
            
    		
         public string PUSH_CODE { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
