//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_AUTH : BasicEntity
    {
         public APP_AUTH(): base(false){ }
         public APP_AUTH(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_AUTH")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> APP_ID { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public string ACCOUNT { get; set; }     
            
    		
         public string PARENT_ORGANIZATION { get; set; }     
            
    		
         public string COMPANY { get; set; }     
            
    		
         public string AREA { get; set; }     
            
    		
         public string HEADQUARTER { get; set; }     
            
    		
         public string BUSINESS_DEPARTMENT { get; set; }     
            
    		
         public string MENUCODE { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
