//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CARPRICE : BasicEntity
    {
         public APP_CARPRICE(): base(false){ }
         public APP_CARPRICE(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_CARPRICE")]
    		
         public long ID { get; set; }     
            
    		
         public string BRAND { get; set; }     
            
    		
         public string SERIES { get; set; }     
            
    		
         public string YEAR { get; set; }     
            
    		
         public string STYLE { get; set; }     
            
    		
         public string TRANSMISSION_KIND { get; set; }     
            
    		
         public string GEAR { get; set; }     
            
    		
         public string SHAPE { get; set; }     
            
    		
         public Nullable<decimal> NEW_PRICE { get; set; }     
            
    		
         public string ENABLED { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public string SWEPT_VOLUME { get; set; }     
            
    		
         public string STYLE_YEAR { get; set; }     
            
    		
         public Nullable<decimal> AVG_WHOLESALE_PRICE { get; set; }     
            
    		
         public Nullable<decimal> AVG_RETAIL_PRICE { get; set; }     
            
    		
         public Nullable<decimal> WELL_WHOLESALE_PRICE { get; set; }     
            
    		
         public Nullable<decimal> WELL_RETAIL_PRICE { get; set; }     
        
    }
}
