//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_JOB : BasicEntity
    {
         public APP_JOB(): base(false){ }
         public APP_JOB(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_JOB")]
    		
         public long ID { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string COM_NAME { get; set; }     
            
    		
         public string COM_PROPERTY { get; set; }     
            
    		
         public string COM_PROPERTY_OTHER { get; set; }     
            
    		
         public string COM_TYPE { get; set; }     
            
    		
         public string COM_TYPE_OTHER { get; set; }     
            
    		
         public string COM_TEL_AREA_CODE { get; set; }     
            
    		
         public string COM_TEL_NO { get; set; }     
            
    		
         public string COM_TEL_EXT { get; set; }     
            
    		
         public string COM_PROVICE { get; set; }     
            
    		
         public string COM_CITY { get; set; }     
            
    		
         public string COM_ADDRESS { get; set; }     
            
    		
         public Nullable<System.DateTime> DATE_COM_REGISTER { get; set; }     
            
    		
         public Nullable<decimal> COM_REGISTER_CAPITAL_AMT { get; set; }     
            
    		
         public Nullable<int> COM_PERSONS { get; set; }     
            
    		
         public string COM_DEPT { get; set; }     
            
    		
         public string COM_POSITION { get; set; }     
            
    		
         public string COM_POSITION_OTHER { get; set; }     
            
    		
         public Nullable<System.DateTime> DATE_JOIN { get; set; }     
            
    		
         public string STATION2_COM { get; set; }     
            
    		
         public Nullable<decimal> SHARE_RATIO { get; set; }     
            
    		
         public string STATION2_COM_OTHER { get; set; }     
            
    		
         public string AEO_TYPE { get; set; }     
            
    		
         public string AEO_CODE { get; set; }     
            
    		
         public string COM_PROFESSION { get; set; }     
            
    		
         public string COM_PROFESSION_DETAIL { get; set; }     
            
    		
         public string WORKING_YEARS { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
