//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CARAGENCY : BasicEntity
    {
         public APP_CARAGENCY(): base(false){ }
         public APP_CARAGENCY(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_CARAGENCY")]
    		
         public long ID { get; set; }     
            
    		
         public string MOTO_NO { get; set; }     
            
    		
         public string MOTO_NAME { get; set; }     
            
    		
         public string IS_USE { get; set; }     
            
    		
         public string MOTO_PRODUCT { get; set; }     
            
    		
         public string MOTO_LEVEL { get; set; }     
        
    }
}
