//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_MSGBOX : BasicEntity
    {
         public APP_MSGBOX(): base(false){ }
         public APP_MSGBOX(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_MSGBOX")]
    		
         public long ID { get; set; }     
            
    		
         public string USERNAME { get; set; }     
            
    		
         public string TITLE { get; set; }     
            
    		
         public string CONTENT { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATETITME { get; set; }     
            
    		
         public string STATUS { get; set; }     
            
    		
         public string PRIORTYLEVEL { get; set; }     
            
    		
         public string CATEGORY { get; set; }     
            
    		
         public string URL { get; set; }     
            
    		
         public string APPCODE { get; set; }     
        
    }
}
