//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_QUANT : BasicEntity
    {
         public APP_QUANT(): base(false){ }
         public APP_QUANT(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_QUANT")]
    		
         public long ID { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string CONTRACT_ID { get; set; }     
            
    		
         public Nullable<decimal> CREDIT_SCORE { get; set; }     
            
    		
         public string REPAYMENT_PLAN { get; set; }     
            
    		
         public Nullable<System.DateTime> SUBMIT_DATE { get; set; }     
            
    		
         public Nullable<System.DateTime> LENDING_DATE { get; set; }     
            
    		
         public string HAS_LENDING { get; set; }     
            
    		
         public string FAIL_REASON { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
