//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CITY_PRODUCT : BasicEntity
    {
         public APP_CITY_PRODUCT(): base(false){ }
         public APP_CITY_PRODUCT(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_CITY_PRODUCT")]
    		
         public long ID { get; set; }     
            
    		
         public string CITY_CODE { get; set; }     
            
    		
         public string PRODUCT_CODE { get; set; }     
            
    		
         public string MENU_GROUP { get; set; }     
            
    		
         public Nullable<short> ENABLE { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
        
    }
}
