//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_NR_LIST : BasicEntity
    {
         public APP_NR_LIST(): base(false){ }
         public APP_NR_LIST(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_NR_LIST")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> APP_ID { get; set; }     
            
    		
         public string NR_CODE { get; set; }     
            
    		
         public string NR_STATUS { get; set; }     
            
    		
         public Nullable<System.DateTime> NR_DATE_SUBMIT_FIRST { get; set; }     
            
    		
         public Nullable<System.DateTime> NR_DATE_UPDATE { get; set; }     
            
    		
         public Nullable<System.DateTime> NR_DATE_APPLY { get; set; }     
            
    		
         public Nullable<short> NR_SEQ { get; set; }     
        public virtual APP_MAIN APP_MAIN { get; set; }
        
    }
}
