//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_EXTEND_RELATION : BasicEntity
    {
         public APP_EXTEND_RELATION(): base(false){ }
         public APP_EXTEND_RELATION(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_EXTEND_RELATION")]
    		
         public long ID { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public string PARENT_APP_CODE { get; set; }     
            
    		
         public Nullable<decimal> SETTLEMENT_AMOUNT { get; set; }     
            
    		
         public Nullable<int> PERIOD_AMOUNT { get; set; }     
            
    		
         public Nullable<int> PERIOD_AMOUNT_USED { get; set; }     
            
    		
         public string PERIOD_STATUS { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public string ACTION_GROUP { get; set; }     
            
    		
         public string PARENT_CONTRACT_ID { get; set; }     
            
    		
         public string CONTRACT_ID { get; set; }     
            
    		
         public string INIT_CONTRACTID { get; set; }     
            
    		
         public string INIT_APP_CODE { get; set; }     
            
    		
         public Nullable<decimal> EXP_RATE { get; set; }     
            
    		
         public Nullable<decimal> EXP_FLOAT_RATE { get; set; }     
            
    		
         public Nullable<int> TIMES_NUMBER_USED { get; set; }     
        
    }
}
