//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_AEO : BasicEntity
    {
         public APP_AEO(): base(false){ }
         public APP_AEO(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_AEO")]
    		
         public long ID { get; set; }     
            
    		
         public string AEO_CODE { get; set; }     
            
    		
         public string AEO_NAME { get; set; }     
            
    		
         public string AEO_TYPE { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public string AEO_CATEGORY { get; set; }     
            
    		
         public Nullable<int> VERSION { get; set; }     
            
    		
         public string ENABLE { get; set; }     
        
    }
}
