//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_SALES : BasicEntity
    {
         public APP_SALES(): base(false){ }
         public APP_SALES(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_SALES")]
    		
         public long ID { get; set; }     
            
    		
         public string SALES_CODE { get; set; }     
            
    		
         public string SALES_NAME { get; set; }     
            
    		
         public string MEMO { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
        
    }
}
