//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_FILE_CHECK : BasicEntity
    {
         public APP_FILE_CHECK(): base(false){ }
         public APP_FILE_CHECK(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_FILE_CHECK")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> APP_ID { get; set; }     
            
    		
         public string FILE_TYPE { get; set; }     
            
    		
         public string FILE_IS_UPLOADED { get; set; }     
        
    }
}
