//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_QUEUE_ASSESS : BasicEntity
    {
         public APP_QUEUE_ASSESS(): base(false){ }
         public APP_QUEUE_ASSESS(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_APP_QUEUE_ASSESS")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> APP_ID { get; set; }     
            
    		
         public Nullable<System.DateTime> CUSTOMER_BOOK_TIME { get; set; }     
            
    		
         public Nullable<System.DateTime> CUSTOMER_ARRIVE_TIME { get; set; }     
            
    		
         public string CUSTOMER_NAME { get; set; }     
            
    		
         public string VEHICLE_NO { get; set; }     
            
    		
         public string SALES_CODE { get; set; }     
            
    		
         public string SALES_NAME { get; set; }     
            
    		
         public string SALES_PHONE { get; set; }     
            
    		
         public string VALUATOR { get; set; }     
            
    		
         public string PRODUCT_LOGO { get; set; }     
            
    		
         public string ASSESS_STATUS { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public Nullable<int> VERSION { get; set; }     
            
    		
         public string REMARK { get; set; }     
            
    		
         public string CUSTOMER_PHONE { get; set; }     
            
    		
         public string VALUATOR_NAME { get; set; }     
        
    }
}
