//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAD_CARJUDGE : BasicEntity
    {
         public PAD_CARJUDGE(): base(false){ }
         public PAD_CARJUDGE(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_PAD_CARJUDGE")]
    		
         public long ID { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public Nullable<decimal> SURFACE_SCORE { get; set; }     
            
    		
         public Nullable<decimal> CARCASE_SCORE { get; set; }     
            
    		
         public Nullable<decimal> INNERTRIM_SCORE { get; set; }     
            
    		
         public Nullable<decimal> CARDEVICE_SCORE { get; set; }     
            
    		
         public string WHOLE_DESCRIPTION { get; set; }     
            
    		
         public Nullable<decimal> JUDGE_PRICE { get; set; }     
            
    		
         public Nullable<int> ENTOURAGE { get; set; }     
            
    		
         public string ENTOURAGE_DESCRIPTION { get; set; }     
            
    		
         public string SUBMIT_STATUS { get; set; }     
            
    		
         public string VALUATOR_BACKGROUND { get; set; }     
            
    		
         public Nullable<decimal> JUDGE_PRICE_BACKGROUND { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
        
    }
}
