//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_APP_MAIN : BasicEntity
    {
        public PRE_APP_MAIN(): base(false){
                this.PRE_APP_AUTH = new HashSet<PRE_APP_AUTH>();
            this.PRE_APP_BANKCARD = new HashSet<PRE_APP_BANKCARD>();
            this.PRE_APP_CUSTOMER = new HashSet<PRE_APP_CUSTOMER>();
            this.PRE_APP_JOB = new HashSet<PRE_APP_JOB>();
            this.PRE_APP_LOAN = new HashSet<PRE_APP_LOAN>();
            this.PRE_APP_STAFF_ONLY = new HashSet<PRE_APP_STAFF_ONLY>();
            this.PRE_APP_CARINFO = new HashSet<PRE_APP_CARINFO>();
        }
        public PRE_APP_MAIN(bool isGenerated = false): base(isGenerated)
        {
            this.PRE_APP_AUTH = new HashSet<PRE_APP_AUTH>();
            this.PRE_APP_BANKCARD = new HashSet<PRE_APP_BANKCARD>();
            this.PRE_APP_CUSTOMER = new HashSet<PRE_APP_CUSTOMER>();
            this.PRE_APP_JOB = new HashSet<PRE_APP_JOB>();
            this.PRE_APP_LOAN = new HashSet<PRE_APP_LOAN>();
            this.PRE_APP_STAFF_ONLY = new HashSet<PRE_APP_STAFF_ONLY>();
            this.PRE_APP_CARINFO = new HashSet<PRE_APP_CARINFO>();
        }
    
            
    	 [Sequence("SEQ_PRE_APP_MAIN")]
    		
         public long ID { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public string LOGO { get; set; }     
            
    		
         public string PRODUCT_CODE { get; set; }     
            
    		
         public string PRODUCT_NAME { get; set; }     
            
    		
         public string APP_STATUS { get; set; }     
            
    		
         public string CUSTOMERTYPE { get; set; }     
            
    		
         public string APPLY_AREA_CODE { get; set; }     
            
    		
         public string APPLY_CITY_CODE { get; set; }     
            
    		
         public string PROD_VERSION { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public string APP_REASON { get; set; }     
            
    		
         public string DFORM_VERSION { get; set; }     
            
    		
         public Nullable<short> HAS_APPLY { get; set; }     
            
    		
         public string ID_NO { get; set; }     
            
    		
         public Nullable<short> PROCESSING { get; set; }     
        public virtual ICollection<PRE_APP_AUTH> PRE_APP_AUTH { get; set; }
        public virtual ICollection<PRE_APP_BANKCARD> PRE_APP_BANKCARD { get; set; }
        public virtual ICollection<PRE_APP_CUSTOMER> PRE_APP_CUSTOMER { get; set; }
        public virtual ICollection<PRE_APP_JOB> PRE_APP_JOB { get; set; }
        public virtual ICollection<PRE_APP_LOAN> PRE_APP_LOAN { get; set; }
        public virtual ICollection<PRE_APP_STAFF_ONLY> PRE_APP_STAFF_ONLY { get; set; }
        public virtual ICollection<PRE_APP_CARINFO> PRE_APP_CARINFO { get; set; }
        
    }
}
