//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_APP_LOAN : BasicEntity
    {
         public PRE_APP_LOAN(): base(false){ }
         public PRE_APP_LOAN(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_PRE_APP_LOAN")]
    		
         public long ID { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string LOAN_PURPOSE { get; set; }     
            
    		
         public string MEMO_OF_LOAN_PURPOSE_OTHER { get; set; }     
            
    		
         public Nullable<decimal> APPLY_AMT { get; set; }     
            
    		
         public Nullable<short> TERMS { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
        public virtual PRE_APP_MAIN PRE_APP_MAIN { get; set; }
        
    }
}
