//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_APP_CUSTOMER : BasicEntity
    {
         public PRE_APP_CUSTOMER(): base(false){ }
         public PRE_APP_CUSTOMER(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_PRE_APP_CUSTOMER")]
    		
         public long ID { get; set; }     
            
    		
         public long APP_ID { get; set; }     
            
    		
         public string NAME { get; set; }     
            
    		
         public string GENDER { get; set; }     
            
    		
         public string ID_NO { get; set; }     
            
    		
         public string ID_TYPE { get; set; }     
            
    		
         public string MARRAGE { get; set; }     
            
    		
         public string EDUCATION { get; set; }     
            
    		
         public string HAS_LOCAL_HOUSE { get; set; }     
            
    		
         public string MORTGAGE_AMT_TOTAL { get; set; }     
            
    		
         public string RESIDENT_STATUS { get; set; }     
            
    		
         public string RESIDENTOTHERS { get; set; }     
            
    		
         public string MOBILE1 { get; set; }     
            
    		
         public string MOBILE2 { get; set; }     
            
    		
         public string MAX_CREDITLIMIT_OF_CCC { get; set; }     
            
    		
         public string NUMS_OF_CCC { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
            
    		
         public Nullable<int> AGE { get; set; }     
            
    		
         public string NUMS_OF_PROVIDE { get; set; }     
            
    		
         public string CREDIT_CARD_TIME { get; set; }     
            
    		
         public string CREDIT_CARD_PAYBACK { get; set; }     
            
    		
         public string OVERDUE_TIMES { get; set; }     
            
    		
         public string MARRAGE_OTHER { get; set; }     
            
    		
         public string FIRST_LOAN_TIME { get; set; }     
            
    		
         public string LAST_LOAN_TIME { get; set; }     
            
    		
         public string LONGEST_LOAN_TIME { get; set; }     
            
    		
         public string ADDED_LOAN_NUMBER { get; set; }     
            
    		
         public string NEED_LOAN_AMT { get; set; }     
            
    		
         public string HOME_TEL_NO { get; set; }     
        public virtual PRE_APP_MAIN PRE_APP_MAIN { get; set; }
        
    }
}
