//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_APP_CARINFO : BasicEntity
    {
         public PRE_APP_CARINFO(): base(false){ }
         public PRE_APP_CARINFO(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_PRE_APP_CARINFO")]
    		
         public long ID { get; set; }     
            
    		
         public Nullable<long> APP_ID { get; set; }     
            
    		
         public string VEHICLE_NO { get; set; }     
            
    		
         public string VIN_NO { get; set; }     
            
    		
         public string ENGINE_NO { get; set; }     
            
    		
         public Nullable<System.DateTime> PARCEL_DATE { get; set; }     
            
    		
         public Nullable<decimal> VEHICLE_AGE { get; set; }     
            
    		
         public string CREATED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATED_TIME { get; set; }     
            
    		
         public string CHANGED_USER { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGED_TIME { get; set; }     
        public virtual PRE_APP_MAIN PRE_APP_MAIN { get; set; }
        
    }
}
