//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APP_CONTRACT : BasicEntity
    {
         public V_APP_CONTRACT(): base(false){ }
         public V_APP_CONTRACT(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_V_APP_CONTRACT")]
    		
         public long ID { get; set; }     
            
    		
         public string APP_CODE { get; set; }     
            
    		
         public string NAME { get; set; }     
            
    		
         public string ID_TYPE { get; set; }     
            
    		
         public string ID_NO { get; set; }     
            
    		
         public string MOBILE1 { get; set; }     
            
    		
         public string RESIDENT_PROVINCE { get; set; }     
            
    		
         public string RESIDENT_CITY { get; set; }     
            
    		
         public string RESIDENT_ADDRESS { get; set; }     
            
    		
         public string EMAIL { get; set; }     
            
    		
         public string BANK_ACCOUNT { get; set; }     
            
    		
         public string BANK_NAME { get; set; }     
            
    		
         public string VEHICLE_NO { get; set; }     
            
    		
         public string CAR_BRAND { get; set; }     
            
    		
         public string CAR_FACTORY { get; set; }     
            
    		
         public string CAR_COLOR { get; set; }     
            
    		
         public string ENGINE_NO { get; set; }     
            
    		
         public string VIN_NO { get; set; }     
            
    		
         public Nullable<short> TERMS { get; set; }     
            
    		
         public string LOAN_PURPOSE { get; set; }     
            
    		
         public Nullable<decimal> RATE { get; set; }     
            
    		
         public string PAYTYPE { get; set; }     
            
    		
         public string MEMO_OF_LOAN_PURPOSE_OTHER { get; set; }     
            
    		
         public string CAR_BRAND_BUYING { get; set; }     
            
    		
         public string CAR_MODEL_BUYING { get; set; }     
            
    		
         public Nullable<decimal> CAR_PRICE_BUYING { get; set; }     
            
    		
         public Nullable<decimal> APPLY_AMT { get; set; }     
            
    		
         public Nullable<decimal> CREDITLIMITADVICE { get; set; }     
            
    		
         public Nullable<decimal> LOAN_AMT { get; set; }     
            
    		
         public Nullable<decimal> LOAN_AMT_OF_CONTRACT { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_MONTHLY_ACCEPTABLE { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_FIRST_MONTHLY { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_LAST_MONTHLY { get; set; }     
            
    		
         public Nullable<decimal> PAY_AMT_MONTHLY { get; set; }     
            
    		
         public Nullable<decimal> DEFAULT_INTEREST_RATIO { get; set; }     
            
    		
         public Nullable<decimal> LATE_FEE_RATIO { get; set; }     
            
    		
         public Nullable<decimal> PREPAYMENT_RATIO { get; set; }     
            
    		
         public Nullable<decimal> SERVICE_CHARGE_RATIO { get; set; }     
            
    		
         public Nullable<decimal> CONSULTATION_CHARGE_RATIO { get; set; }     
            
    		
         public string RATE_TYPE { get; set; }     
            
    		
         public string CURRENCY { get; set; }     
            
    		
         public Nullable<decimal> RESERVES_RATIO { get; set; }     
            
    		
         public Nullable<decimal> SERVICE_CHARGE_AMT { get; set; }     
            
    		
         public Nullable<decimal> CONSULTATION_CHARGE_AMT { get; set; }     
            
    		
         public Nullable<decimal> RESERVES_AMT { get; set; }     
            
    		
         public Nullable<decimal> RISK_RATIO { get; set; }     
            
    		
         public Nullable<decimal> RISK_AMT { get; set; }     
            
    		
         public Nullable<decimal> CHANNEL_EXPENSE_RATIO { get; set; }     
            
    		
         public string COLLATERAL_TYPE { get; set; }     
            
    		
         public string COLLATERAL_STATUS { get; set; }     
            
    		
         public string HOUSE_TYPE { get; set; }     
            
    		
         public string HOUSE_PROVINCE { get; set; }     
            
    		
         public string HOUSE_CITY { get; set; }     
            
    		
         public string HOUSE_ADDRESS { get; set; }     
            
    		
         public Nullable<decimal> COVERED_AREA { get; set; }     
            
    		
         public Nullable<short> COMPLETE_AGE { get; set; }     
            
    		
         public Nullable<short> PROPERTYRIGHT_PERSONS { get; set; }     
            
    		
         public string LOAN_BANK { get; set; }     
            
    		
         public Nullable<decimal> REMAIN_PRINCIPAL { get; set; }     
            
    		
         public Nullable<decimal> ASSESSMENT_VALUE { get; set; }     
            
    		
         public string COLLATERAL_STATUS_OTHER { get; set; }     
            
    		
         public string HOUSE_TYPE_OTHER { get; set; }     
            
    		
         public string POSTCODE { get; set; }     
            
    		
         public string RESIDENT_TEL_NO { get; set; }     
            
    		
         public string REGISTER_PROVINCE { get; set; }     
            
    		
         public string REGISTER_CITY { get; set; }     
            
    		
         public string REGISTER_ADDRESS { get; set; }     
            
    		
         public string BANK_SUB { get; set; }     
            
    		
         public Nullable<decimal> CAR_SELLINGPRICE { get; set; }     
        
    }
}
