//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APPMAIN : BasicEntity
    {
         public V_APPMAIN(): base(false){ }
         public V_APPMAIN(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_V_APPMAIN")]
    		
         public long APPID { get; set; }     
            
    		
         public string APPCODE { get; set; }     
            
    		
         public string LOGO { get; set; }     
            
    		
         public string PRODUCTCODE { get; set; }     
            
    		
         public string CUSTOMERNAME { get; set; }     
            
    		
         public Nullable<decimal> APPLYAMT { get; set; }     
            
    		
         public Nullable<decimal> LOANAMTOFCONTRACT { get; set; }     
            
    		
         public string SALESNAME { get; set; }     
            
    		
         public string SALESNO { get; set; }     
            
    		
         public string CSADNAME { get; set; }     
            
    		
         public string CSADNO { get; set; }     
            
    		
         public string APPSTATUS { get; set; }     
            
    		
         public string APPSTATUSNAME { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATEDTIME { get; set; }     
            
    		
         public Nullable<System.DateTime> UPDATETIME { get; set; }     
            
    		
         public Nullable<decimal> SORTING { get; set; }     
            
    		
         public string APPNRSDSTATUS { get; set; }     
            
    		
         public string APPAPPR1SDSTATUS { get; set; }     
            
    		
         public string CREATEDUSER { get; set; }     
            
    		
         public string CUSTOMERIDCARD { get; set; }     
            
    		
         public Nullable<decimal> EXTENDAMTOFCONTRACT { get; set; }     
            
    		
         public string PRODUCTNAME { get; set; }     
            
    		
         public string BUSINESSDEPARTMENT { get; set; }     
        
    }
}
