//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QK.QAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRE_APPMAIN : BasicEntity
    {
         public V_PRE_APPMAIN(): base(false){ }
         public V_PRE_APPMAIN(bool isGenerated = false) : base(isGenerated) { }
            
    	 [Sequence("SEQ_V_PRE_APPMAIN")]
    		
         public long APPID { get; set; }     
            
    		
         public string APPCODE { get; set; }     
            
    		
         public string LOGO { get; set; }     
            
    		
         public Nullable<short> HAS_APPLY { get; set; }     
            
    		
         public string CUSTOMERNAME { get; set; }     
            
    		
         public string CUSTOMERIDCARD { get; set; }     
            
    		
         public string PRODUCTCODE { get; set; }     
            
    		
         public string PRODUCTNAME { get; set; }     
            
    		
         public string APPCITYNAME { get; set; }     
            
    		
         public Nullable<decimal> APPLYAMT { get; set; }     
            
    		
         public string APPSTATUS { get; set; }     
            
    		
         public Nullable<decimal> SORTING { get; set; }     
            
    		
         public string APPSTATUSNAME { get; set; }     
            
    		
         public Nullable<System.DateTime> CREATEDTIME { get; set; }     
            
    		
         public Nullable<System.DateTime> CHANGEDTIME { get; set; }     
            
    		
         public string CUSTOMERMOBILE1 { get; set; }     
            
    		
         public string CUSTOMERMOBILE2 { get; set; }     
            
    		
         public string SALESNAME { get; set; }     
            
    		
         public string SALESCODE { get; set; }     
        
    }
}
