//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Motor
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string NumCode
	{
		get;
		set;
	}

	public virtual Car Car
	{
		get;
		set;
	}

}

