//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Programmer
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual Computer GetComputer(string numCode)
	{
		throw new System.NotImplementedException();
	}

}

