//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tree
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string Root
	{
		get;
		set;
	}

	public virtual string Trunk
	{
		get;
		set;
	}

	public virtual string Leaf
	{
		get;
		set;
	}

	public virtual double Height
	{
		get;
		set;
	}

	public virtual void Drink()
	{
		throw new System.NotImplementedException();
	}

}

